import type { FormSchemaGetter } from '#/adapter/form';

/** 投信新增/编辑表单 schema（收益率百分数字段在弹窗内转换为小数提交） */
export const fundFormSchema: FormSchemaGetter = () => [
  {
    component: 'Input',
    dependencies: { show: () => false, triggerFields: [''] },
    fieldName: 'id',
    label: 'ID',
  },
  {
    component: 'Input',
    dependencies: { show: () => false, triggerFields: [''] },
    fieldName: 'poster',
    label: 'poster',
  },
  {
    component: 'Input',
    fieldName: 'code',
    label: '投信代码',
    rules: 'required',
    formItemClass: 'col-span-1',
  },
  {
    component: 'Input',
    fieldName: 'symbol',
    label: '符号',
    rules: 'required',
    formItemClass: 'col-span-1',
  },
  {
    component: 'Input',
    fieldName: 'name',
    label: '投信名称',
    rules: 'required',
    formItemClass: 'col-span-1',
  },
  {
    component: 'Input',
    fieldName: 'company',
    label: '公司',
    rules: 'required',
    formItemClass: 'col-span-1',
  },
  {
    component: 'Input',
    fieldName: 'ev',
    label: '估值',
    formItemClass: 'col-span-1',
  },
  {
    component: 'InputNumber',
    componentProps: { class: 'w-full', min: 0, precision: 2 },
    fieldName: 'price',
    label: '投信价格',
    formItemClass: 'col-span-1',
  },
  {
    component: 'RadioGroup',
    componentProps: {
      options: [
        { label: 'USD', value: 'USD' },
        { label: 'EUR', value: 'EUR' },
      ],
    },
    defaultValue: 'USD',
    fieldName: 'currency',
    label: '币种',
    formItemClass: 'col-span-2',
  },
  {
    component: 'Input',
    componentProps: { placeholder: '产品描述' },
    fieldName: 'description',
    label: '产品描述',
    formItemClass: 'col-span-2',
  },
  {
    component: 'InputNumber',
    componentProps: { class: 'w-full', min: 0, precision: 2 },
    fieldName: 'rateMinPct',
    label: '最低收益率(%)',
    formItemClass: 'col-span-1',
  },
  {
    component: 'InputNumber',
    componentProps: { class: 'w-full', min: 0, precision: 2 },
    fieldName: 'rateMaxPct',
    label: '最高收益率(%)',
    formItemClass: 'col-span-1',
  },
  {
    component: 'InputNumber',
    componentProps: { class: 'w-full', min: 0, precision: 2 },
    fieldName: 'ratePct',
    label: '固定收益率(%)',
    rules: 'required',
    formItemClass: 'col-span-1',
  },
  {
    component: 'InputNumber',
    componentProps: { class: 'w-full', min: 0, precision: 2 },
    fieldName: 'minAmount',
    label: '最低投入金额',
    rules: 'required',
    formItemClass: 'col-span-1',
  },
  {
    component: 'InputNumber',
    componentProps: { class: 'w-full', min: 0, precision: 2 },
    fieldName: 'maxAmount',
    label: '最大投入金额',
    rules: 'required',
    formItemClass: 'col-span-1',
  },
  {
    component: 'InputNumber',
    componentProps: { class: 'w-full', min: 0, precision: 2 },
    fieldName: 'minAppendAmount',
    label: '最低追投金额',
    formItemClass: 'col-span-1',
  },
  {
    component: 'InputNumber',
    componentProps: { class: 'w-full', min: 1, precision: 0 },
    fieldName: 'period',
    label: '周期(天)',
    rules: 'required',
    formItemClass: 'col-span-1',
  },
  {
    component: 'RadioGroup',
    componentProps: {
      options: [
        { label: '进行中', value: 0 },
        { label: '已售罄', value: 1 },
      ],
    },
    defaultValue: 0,
    fieldName: 'soldOut',
    label: '状态',
    formItemClass: 'col-span-1',
  },
  {
    component: 'InputNumber',
    componentProps: { class: 'w-full', min: 0, precision: 0 },
    fieldName: 'sort',
    label: '排序',
    rules: 'required',
    formItemClass: 'col-span-1',
  },
];
